### PR TITLE
🕸️ Implementing GPMA for Seastar

### PR DESCRIPTION
**Pull request by nithinmanoj10**
Seastar uses PCSR for representing and storing dynamic graphs. We will now try to represent dynamic graphs using a GPMA instead on the GPU for possibly faster operations on the graph.

### CODE REVIEW

**Comment by nithinmanoj10** [comment]
# :sparkles: Functionalities to add to GPMA module

Need to add the following functions to the GPMA python binding so it can be easily used with SeastarGraph abstraction.

- [ ] add_edge_list()
- [ ] in_degrees and num_neighbours for each vertex
- [ ] get_csr_arrays()
- [ ] label_edges()
- [ ] find_edge_id()
- [ ] delete_edge_list()

**Comment by JoelMathewC** [comment]
To handle builds for PCSR cpp and GPMA cu files we can use the following in `setup.py` https://setuptools.pypa.io/en/latest/userguide/ext_modules.html

**Comment by nithinmanoj10** [comment]
## CSR PTRS

We can use [this](https://pybind11.readthedocs.io/en/stable/advanced/smart_ptrs.html) for passing pointers to python

**Comment by JoelMathewC** [comment]
## Dealing with Seastar interacting with SeastarGraph

To deal with dynamic graph updates, we will use `get_graph_for_timestamp` in the training loop and then maintain the timestamp of each graph that is passed as input in an array in the execution state. Then when backward is called we pop that stack and get the corresponding graph and then use `get_graph_reverse_for_timestamp`. 

Additionally, make sure that interfaces for `SeastarGraph`, `SeastarDynamicGraph` only include functions exposed to the public. All private functions can be implemented normally.

**Comment by JoelMathewC** [comment]
Figured out why GPMA is so slow, it turns out the issue is because we were editing `thrust::device_vector` directly. This apparently makes repeated calls to `cudaMemcpy` and is hence advised to be used sparingly in the [thrust docs](https://docs.nvidia.com/cuda/thrust/)

**Pull request merged**
